<a href="https://colab.research.google.com/github/vaibhavbahuguna11/Assignment-1/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Create a null vector of size 10 but the fifth value which is 1.**

In [ ]:
import numpy as np

ary = np.zeros((10))
ary[4] = 1

print(ary)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**2. Create a vector with values ranging from 10 to 49.**

In [ ]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**3. Create a 3x3 matrix with values ranging from 0 to 8d**

In [ ]:
b = np.arange(0,9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**4. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [ ]:
c = np.array([1,2,0,0,4,0])
d = np.nonzero(c)
print(f"The indices of non-zero elements are {d} ")

The indices of non-zero elements are (array([0, 1, 4]),) 


**5. Create a 10x10 array with random values and find the minimum and maximum values.***

In [ ]:
new_ary = np.random.randn(10,10)
print(f"The 10 X 10 array \n{new_ary}")

max_val = new_ary.max()
min_val = new_ary.min()
print(f"The maximum value is {max_val}")
print(f"The minimum vallue is {min_val}")

The 10 X 10 array 
[[-0.60029614  0.20687708 -1.20153129 -0.27845478 -1.13011516 -0.20201913
   0.53241751 -1.03935838  1.4338923  -0.91238451]
 [-0.40328869 -0.38981117  0.24633737  0.28498773  0.7025712   0.72119934
  -0.05485744  0.0605281   0.17823066 -0.42118407]
 [-0.55134049 -1.11833994  0.84571516 -0.74967013 -1.27928635 -0.17208718
  -1.60045415 -0.71722416  0.14405483 -0.09301244]
 [-2.27503374 -0.05208431 -0.25936256  0.36751775  0.83740874 -0.98168273
   0.72637116 -0.01189588  0.35861261  1.79634908]
 [ 0.77462715 -2.0804787  -1.6442368  -0.01213797 -0.82243624 -3.06926186
   1.1796116  -0.64934041 -1.32246837 -0.87558089]
 [-1.62171444 -0.43455101 -0.97157751 -0.52525642  0.18374475  1.66082366
   0.74057198 -0.79503768  0.58836125  1.29795207]
 [-0.93514697  0.19168533 -0.96125307 -0.67617893  0.45237513 -0.16190435
   0.17677711 -0.65366262  1.60984077 -0.02002504]
 [ 1.30499229 -0.67048424  1.51047281 -0.29647686 -0.16244016  0.18301794
  -0.06530953  0.00726242  1.172

**6. Create a random vector of size 30 and find the mean value**

In [ ]:
rand_ary = np.random.random(30)
mean_val = rand_ary.mean()
print(mean_val)

0.3996376856932038
